"""Fix posts model

Revision ID: 10b76f6d3793
Revises: fda31613b3e3
Create Date: 2022-11-15 02:53:17.291841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b76f6d3793'
down_revision = 'fda31613b3e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
